#pragma once

#include <array>

namespace cv {

enum class AstMatcherKind {
  FunctionCall,
  MemberCall,
  MemberCallUIntArg,
  MemberRangeEmpty,
  NegatedMemberCallUIntArg,
  TypeName,
  BinaryEquality,
  NestedFunctionCall,
};

struct AstMatcherSpec {
  const char *bindName;
  const char *marker;
  AstMatcherKind kind;
  const char *name;
  const char *nestedName;
};

inline constexpr std::array<AstMatcherSpec, 89>
    kAstMatcherSpecs{{
        {"vector-add-zero", "probe.vector.add-zero", AstMatcherKind::NestedFunctionCall, "m_SplatOrPoison", "m_Zero"},
        {"vector-mul-one", "probe.vector.mul-one", AstMatcherKind::NestedFunctionCall, "m_SplatOrPoison", "m_One"},
        {"vector-xor-self", "probe.vector.xor-self", AstMatcherKind::FunctionCall, "VectorXorSelf", ""},
        {"vector-xor-self", "probe.vector.xor-self", AstMatcherKind::FunctionCall, "::llvm::VectorXorSelf", ""},
        {"vector-shuffle-identity", "probe.vector.shuffle-identity", AstMatcherKind::FunctionCall, "isIdentityMask", ""},
        {"vector-shuffle-identity", "probe.vector.shuffle-identity", AstMatcherKind::FunctionCall, "::llvm::isIdentityMask", ""},
        {"vector-shuffle-identity", "probe.vector.shuffle-identity", AstMatcherKind::FunctionCall, "isIdentityWithExtract", ""},
        {"vector-shuffle-identity", "probe.vector.shuffle-identity", AstMatcherKind::FunctionCall, "::llvm::isIdentityWithExtract", ""},
        {"vector-shuffle-splat", "probe.vector.shuffle-splat", AstMatcherKind::FunctionCall, "isSplatMask", ""},
        {"vector-shuffle-splat", "probe.vector.shuffle-splat", AstMatcherKind::FunctionCall, "::llvm::isSplatMask", ""},
        {"vector-extract-insert", "probe.vector.extract-insert", AstMatcherKind::FunctionCall, "sameLaneExtractInsert", ""},
        {"vector-extract-insert", "probe.vector.extract-insert", AstMatcherKind::FunctionCall, "::llvm::sameLaneExtractInsert", ""},
        {"vector-reduction-add-zero", "probe.vector.reduction-add-zero", AstMatcherKind::FunctionCall, "ReductionAddZero", ""},
        {"vector-reduction-add-zero", "probe.vector.reduction-add-zero", AstMatcherKind::FunctionCall, "::llvm::ReductionAddZero", ""},
        {"vector-reduction-add-zero", "probe.vector.reduction-add-zero", AstMatcherKind::FunctionCall, "CreateAddReduce", ""},
        {"vector-reduction-add-zero", "probe.vector.reduction-add-zero", AstMatcherKind::FunctionCall, "::llvm::CreateAddReduce", ""},
        {"vector-reduction-add-zero", "probe.vector.reduction-add-zero", AstMatcherKind::FunctionCall, "vector_reduce_add", ""},
        {"vector-reduction-add-zero", "probe.vector.reduction-add-zero", AstMatcherKind::FunctionCall, "::llvm::vector_reduce_add", ""},
        {"vector-sub-zero", "probe.vector.sub-zero", AstMatcherKind::FunctionCall, "VectorSubZero", ""},
        {"vector-sub-zero", "probe.vector.sub-zero", AstMatcherKind::FunctionCall, "::llvm::VectorSubZero", ""},
        {"vector-or-zero", "probe.vector.or-zero", AstMatcherKind::FunctionCall, "VectorOrZero", ""},
        {"vector-or-zero", "probe.vector.or-zero", AstMatcherKind::FunctionCall, "::llvm::VectorOrZero", ""},
        {"vector-and-allones", "probe.vector.and-allones", AstMatcherKind::FunctionCall, "VectorAndAllOnes", ""},
        {"vector-and-allones", "probe.vector.and-allones", AstMatcherKind::FunctionCall, "::llvm::VectorAndAllOnes", ""},
        {"vector-smin", "probe.vector.smin", AstMatcherKind::FunctionCall, "CreateSMin", ""},
        {"vector-smin", "probe.vector.smin", AstMatcherKind::FunctionCall, "::llvm::CreateSMin", ""},
        {"vector-smin", "probe.vector.smin", AstMatcherKind::FunctionCall, "VectorSMin", ""},
        {"vector-smin", "probe.vector.smin", AstMatcherKind::FunctionCall, "::llvm::VectorSMin", ""},
        {"vector-smax", "probe.vector.smax", AstMatcherKind::FunctionCall, "CreateSMax", ""},
        {"vector-smax", "probe.vector.smax", AstMatcherKind::FunctionCall, "::llvm::CreateSMax", ""},
        {"vector-smax", "probe.vector.smax", AstMatcherKind::FunctionCall, "VectorSMax", ""},
        {"vector-smax", "probe.vector.smax", AstMatcherKind::FunctionCall, "::llvm::VectorSMax", ""},
        {"vector-umin", "probe.vector.umin", AstMatcherKind::FunctionCall, "CreateUMin", ""},
        {"vector-umin", "probe.vector.umin", AstMatcherKind::FunctionCall, "::llvm::CreateUMin", ""},
        {"vector-umin", "probe.vector.umin", AstMatcherKind::FunctionCall, "VectorUMin", ""},
        {"vector-umin", "probe.vector.umin", AstMatcherKind::FunctionCall, "::llvm::VectorUMin", ""},
        {"vector-umax", "probe.vector.umax", AstMatcherKind::FunctionCall, "CreateUMax", ""},
        {"vector-umax", "probe.vector.umax", AstMatcherKind::FunctionCall, "::llvm::CreateUMax", ""},
        {"vector-umax", "probe.vector.umax", AstMatcherKind::FunctionCall, "VectorUMax", ""},
        {"vector-umax", "probe.vector.umax", AstMatcherKind::FunctionCall, "::llvm::VectorUMax", ""},
        {"vector-abs", "probe.vector.abs", AstMatcherKind::FunctionCall, "CreateAbs", ""},
        {"vector-abs", "probe.vector.abs", AstMatcherKind::FunctionCall, "::llvm::CreateAbs", ""},
        {"vector-abs", "probe.vector.abs", AstMatcherKind::FunctionCall, "VectorAbs", ""},
        {"vector-abs", "probe.vector.abs", AstMatcherKind::FunctionCall, "::llvm::VectorAbs", ""},
        {"vector-insert-extract-identity", "probe.vector.insert-extract-identity", AstMatcherKind::FunctionCall, "insertExtractIdentity", ""},
        {"vector-insert-extract-identity", "probe.vector.insert-extract-identity", AstMatcherKind::FunctionCall, "::llvm::insertExtractIdentity", ""},
        {"vector-reduction-add-single-lane", "probe.vector.reduction-add-single-lane", AstMatcherKind::FunctionCall, "ReductionAddSingleLane", ""},
        {"vector-reduction-add-single-lane", "probe.vector.reduction-add-single-lane", AstMatcherKind::FunctionCall, "::llvm::ReductionAddSingleLane", ""},
        {"m-zero", "probe.instcombine.add-zero", AstMatcherKind::FunctionCall, "m_Zero", ""},
        {"m-sub", "probe.instcombine.sub-zero", AstMatcherKind::FunctionCall, "m_Sub", ""},
        {"m-one", "probe.instcombine.mul-one", AstMatcherKind::FunctionCall, "m_One", ""},
        {"m-or", "probe.instcombine.or-zero", AstMatcherKind::FunctionCall, "m_Or", ""},
        {"m-allones", "probe.instcombine.and-allones", AstMatcherKind::FunctionCall, "m_AllOnes", ""},
        {"m-and", "probe.instcombine.and-self", AstMatcherKind::FunctionCall, "m_And", ""},
        {"xor-self", "probe.instcombine.xor-self", AstMatcherKind::BinaryEquality, "", ""},
        {"xor-self", "probe.instcombine.xor-self", AstMatcherKind::FunctionCall, "m_Xor", ""},
        {"dead-inst", "probe.dce.dead-instruction", AstMatcherKind::FunctionCall, "isInstructionTriviallyDead", ""},
        {"dead-inst", "probe.dce.dead-instruction", AstMatcherKind::FunctionCall, "::llvm::isInstructionTriviallyDead", ""},
        {"dead-global-init", "probe.globalopt.dead-initializer", AstMatcherKind::FunctionCall, "isGlobalInitializerDead", ""},
        {"dead-global-init", "probe.globalopt.dead-initializer", AstMatcherKind::FunctionCall, "::llvm::isGlobalInitializerDead", ""},
        {"unreachable", "probe.simplifycfg.unreachable-block", AstMatcherKind::TypeName, "UnreachableInst", ""},
        {"diamond", "probe.simplifycfg.diamond", AstMatcherKind::MemberCall, "getSinglePredecessor", ""},
        {"branch-chain", "probe.simplifycfg.branch-chain", AstMatcherKind::TypeName, "SwitchInst", ""},
        {"promotable-alloca", "probe.mem2reg.promotable-alloca", AstMatcherKind::FunctionCall, "isAllocaPromotable", ""},
        {"promotable-alloca", "probe.mem2reg.promotable-alloca", AstMatcherKind::FunctionCall, "::llvm::isAllocaPromotable", ""},
        {"store-load-forward", "probe.mem2reg.store-load-forward", AstMatcherKind::FunctionCall, "rewriteSingleStoreAlloca", ""},
        {"store-load-forward", "probe.mem2reg.store-load-forward", AstMatcherKind::FunctionCall, "::llvm::rewriteSingleStoreAlloca", ""},
        {"dead-store", "probe.dse.dead-store", AstMatcherKind::FunctionCall, "isRemovable", ""},
        {"dead-store", "probe.dse.dead-store", AstMatcherKind::FunctionCall, "::llvm::isRemovable", ""},
        {"overwritten-store", "probe.dse.overwritten-store", AstMatcherKind::FunctionCall, "isOverwrite", ""},
        {"overwritten-store", "probe.dse.overwritten-store", AstMatcherKind::FunctionCall, "::llvm::isOverwrite", ""},
        {"redundant-load", "probe.instcombine.redundant-load", AstMatcherKind::FunctionCall, "FindAvailableLoadedValue", ""},
        {"redundant-load", "probe.instcombine.redundant-load", AstMatcherKind::FunctionCall, "::llvm::FindAvailableLoadedValue", ""},
        {"unused-alloca", "probe.cleanup.unused-alloca", AstMatcherKind::MemberCallUIntArg, "hasNUses", "0"},
        {"unused-alloca", "probe.cleanup.unused-alloca", AstMatcherKind::MemberRangeEmpty, "users", "empty"},
        {"unused-alloca", "probe.cleanup.unused-alloca", AstMatcherKind::NegatedMemberCallUIntArg, "hasNUsesOrMore", "1"},
        {"unused-alloca", "probe.cleanup.unused-alloca", AstMatcherKind::MemberCall, "use_empty", ""},
        {"unused-alloca", "probe.cleanup.unused-alloca", AstMatcherKind::MemberCall, "user_empty", ""},
        {"loop-header", "probe.loop.canonical-header", AstMatcherKind::MemberCall, "getHeader", ""},
        {"induction-phi", "probe.loop.induction-phi", AstMatcherKind::TypeName, "PHINode", ""},
        {"simple-trip-count", "probe.loop.simple-trip-count", AstMatcherKind::FunctionCall, "getSmallConstantTripCount", ""},
        {"simple-trip-count", "probe.loop.simple-trip-count", AstMatcherKind::FunctionCall, "::llvm::getSmallConstantTripCount", ""},
        {"invariant-op", "probe.licm.invariant-op", AstMatcherKind::FunctionCall, "isLoopInvariant", ""},
        {"invariant-op", "probe.licm.invariant-op", AstMatcherKind::FunctionCall, "::llvm::isLoopInvariant", ""},
        {"invariant-op", "probe.licm.invariant-op", AstMatcherKind::FunctionCall, "makeLoopInvariant", ""},
        {"invariant-op", "probe.licm.invariant-op", AstMatcherKind::FunctionCall, "::llvm::makeLoopInvariant", ""},
        {"dead-loop-inst", "probe.dce.dead-loop-instruction", AstMatcherKind::FunctionCall, "isDeadLoopInstruction", ""},
        {"dead-loop-inst", "probe.dce.dead-loop-instruction", AstMatcherKind::FunctionCall, "::llvm::isDeadLoopInstruction", ""},
        {"loop-exit", "probe.simplifycfg.loop-exit", AstMatcherKind::MemberCall, "getExitBlock", ""},
    }};

} // namespace cv
