// GENERATED by tools/cv-generate-vector-intent-header.py from
// constraints/semantic_facts.json -- DO NOT EDIT.
//
// X-macro: EMIT(marker, shape, operation, identity, rewrite, result).
#ifndef O2T_GENERATED_VECTOR_INTENT_PARTS_H
#define O2T_GENERATED_VECTOR_INTENT_PARTS_H

#define CV_FOR_EACH_VECTOR_INTENT_MARKER(EMIT) \
  EMIT("probe.vector.abs", "fixed-vector", "abs", "absolute-value", "preserve-vector", "vector") \
  EMIT("probe.vector.add-zero", "fixed-vector", "add", "zero", "replace-with-lhs", "vector") \
  EMIT("probe.vector.and-allones", "fixed-vector", "and", "allones", "replace-with-lhs", "vector") \
  EMIT("probe.vector.extract-insert", "fixed-vector", "extract-insert", "same-lane", "replace-with-inserted-scalar", "scalar") \
  EMIT("probe.vector.insert-extract-identity", "fixed-vector", "insert-extract", "same-lane", "preserve-vector", "vector") \
  EMIT("probe.vector.mul-one", "fixed-vector", "mul", "one", "replace-with-lhs", "vector") \
  EMIT("probe.vector.or-zero", "fixed-vector", "or", "zero", "replace-with-lhs", "vector") \
  EMIT("probe.vector.reduction-add-single-lane", "fixed-vector", "reduction-add", "single-live-lane", "replace-with-lane", "scalar") \
  EMIT("probe.vector.reduction-add-zero", "fixed-vector", "reduction-add", "zero-vector", "reduce-to-zero", "scalar") \
  EMIT("probe.vector.scalable.add-zero", "scalable-vector", "add", "zero", "replace-with-lhs", "vector") \
  EMIT("probe.vector.scalable.and-allones", "scalable-vector", "and", "allones", "replace-with-lhs", "vector") \
  EMIT("probe.vector.scalable.mul-one", "scalable-vector", "mul", "one", "replace-with-lhs", "vector") \
  EMIT("probe.vector.scalable.or-zero", "scalable-vector", "or", "zero", "replace-with-lhs", "vector") \
  EMIT("probe.vector.scalable.reduction-add-zero", "scalable-vector", "reduction-add", "zero-vector", "reduce-to-zero-splat", "vector") \
  EMIT("probe.vector.scalable.sub-zero", "scalable-vector", "sub", "zero", "replace-with-lhs", "vector") \
  EMIT("probe.vector.scalable.xor-self", "scalable-vector", "xor", "same-value", "replace-with-zero", "vector") \
  EMIT("probe.vector.shuffle-identity", "fixed-vector", "shuffle", "identity-mask", "preserve-vector", "vector") \
  EMIT("probe.vector.shuffle-splat", "fixed-vector", "shuffle", "splat-mask", "replace-with-lane-splat", "vector") \
  EMIT("probe.vector.smax", "fixed-vector", "max", "signed-max", "preserve-vector", "vector") \
  EMIT("probe.vector.smin", "fixed-vector", "min", "signed-min", "preserve-vector", "vector") \
  EMIT("probe.vector.sub-zero", "fixed-vector", "sub", "zero", "replace-with-lhs", "vector") \
  EMIT("probe.vector.umax", "fixed-vector", "max", "unsigned-max", "preserve-vector", "vector") \
  EMIT("probe.vector.umin", "fixed-vector", "min", "unsigned-min", "preserve-vector", "vector") \
  EMIT("probe.vector.xor-self", "fixed-vector", "xor", "same-value", "replace-with-zero", "vector")

#endif  // O2T_GENERATED_VECTOR_INTENT_PARTS_H
