#pragma once
// Generated by cv-generate-klee-feedback.py. Do not edit by hand.
//
// Covered probe markers fed back into the KLEE harness: with
// -DO2T_KLEE_FEEDBACK the harness assumes isNovelCoverage(), pruning
// configs that only re-derive already-covered markers.

#include "o2t/GeneratedProbeMarkerMap.h"

#include <cstddef>
#include <cstring>

namespace cv {

inline constexpr const char *kCoveredMarkers[] = {
    nullptr,
};

inline constexpr std::size_t kCoveredMarkerCount = 0;

inline bool markerCovered(const char *marker) {
  for (std::size_t i = 0; i < kCoveredMarkerCount; ++i) {
    if (std::strcmp(kCoveredMarkers[i], marker) == 0) {
      return true;
    }
  }
  return false;
}

// True when the config hits at least one marker not yet in the covered set.
inline bool isNovelCoverage(const PassProbeCoverage &coverage) {
  for (const ProbeMarkerMetadata &meta : kProbeMarkerMetadata) {
    if (coverage.*meta.coverage && !markerCovered(meta.marker)) {
      return true;
    }
  }
  return false;
}

} // namespace cv
