// GENERATED by tools/cv-generate-idiom-header.py from
// constraints/llvm_idioms.json -- DO NOT EDIT.
//
// X-macro: invoke CV_FOR_EACH_GENERATED_OPERATION_IDIOM(AddOperation) where
// AddOperation is callable as AddOperation(name, {matchers}, {builders}, commutative).
#ifndef O2T_GENERATED_LLVM_IDIOMS_H
#define O2T_GENERATED_LLVM_IDIOMS_H

#define CV_FOR_EACH_GENERATED_OPERATION_IDIOM(AddOperation) \
  AddOperation("add", {"m_Add", "m_c_Add"}, {"CreateAdd"}, true); \
  AddOperation("and", {"m_And", "m_c_And"}, {"CreateAnd"}, true); \
  AddOperation("ashr", {"m_AShr"}, {"CreateAShr"}, false); \
  AddOperation("lshr", {"m_LShr"}, {"CreateLShr"}, false); \
  AddOperation("mul", {"m_Mul", "m_c_Mul"}, {"CreateMul"}, true); \
  AddOperation("or", {"m_Or", "m_c_Or"}, {"CreateOr"}, true); \
  AddOperation("sdiv", {"m_SDiv"}, {"CreateSDiv"}, false); \
  AddOperation("shl", {"m_Shl"}, {"CreateShl"}, false); \
  AddOperation("srem", {"m_SRem"}, {"CreateSRem"}, false); \
  AddOperation("sub", {"m_Sub"}, {"CreateSub"}, false); \
  AddOperation("udiv", {"m_UDiv"}, {"CreateUDiv"}, false); \
  AddOperation("urem", {"m_URem"}, {"CreateURem"}, false); \
  AddOperation("xor", {"m_Xor"}, {"CreateXor"}, true);

// EMIT(identity, value, matcher)
#define CV_FOR_EACH_GENERATED_IDENTITY_CONSTANT(EMIT) \
  EMIT("allones", "4294967295", "m_AllOnes") \
  EMIT("one", "1", "m_One") \
  EMIT("zero", "0", "m_Zero")

#endif  // O2T_GENERATED_LLVM_IDIOMS_H
