#!/usr/bin/env python3
"""Generate the C++ miner's vector-marker -> source-intent-parts table from
constraints/semantic_facts.json.

`vectorIntentPartsForMarker` in cv-mine-pass-source-ast.cpp used to be a hardcoded
suffix ladder duplicating the per-marker {shape, operation, identity, rewrite,
result} already in semantic_facts.json. This emits that table as an X-macro header
so the registry is the single source of truth -- adding a probe.vector.* marker is
now a JSON edit that propagates to the miner.

Only `probe.vector.*` markers are emitted (the function is gated by
isVectorMarker == starts_with("probe.vector.")); probe.slp.* and scalar markers
flow through other miner paths and must NOT appear here.

  --out FILE     write the generated header
  --check FILE   regenerate and diff against FILE; exit 1 on drift (CI guard)
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FACTS = ROOT / "constraints" / "semantic_facts.json"
DEFAULT_OUT = ROOT / "include" / "o2t" / "GeneratedVectorIntentParts.h"
GUARD = "O2T_GENERATED_VECTOR_INTENT_PARTS_H"
FIELDS = ("shape", "operation", "identity", "rewrite", "result")


def render(facts_path: Path) -> str:
    data = json.loads(facts_path.read_text(encoding="utf-8"))
    records = data if isinstance(data, list) else data.get("records", [])
    rows: list[tuple[str, ...]] = []
    for record in records:
        if not isinstance(record, dict):
            continue
        marker = record.get("marker")
        facts = record.get("semantic_facts")
        if not isinstance(marker, str) or not marker.startswith("probe.vector."):
            continue
        if not isinstance(facts, dict):
            continue
        values = [str(facts.get(field) or "") for field in FIELDS]
        if not all(values):
            raise ValueError(f"vector marker {marker} is missing a field: "
                             f"{dict(zip(FIELDS, values))}")
        rows.append((marker, *values))
    rows.sort(key=lambda r: r[0])
    if not rows:
        raise ValueError("no probe.vector.* markers found in semantic_facts.json")

    lines = [
        "// GENERATED by tools/cv-generate-vector-intent-header.py from",
        "// constraints/semantic_facts.json -- DO NOT EDIT.",
        "//",
        "// X-macro: EMIT(marker, shape, operation, identity, rewrite, result).",
        f"#ifndef {GUARD}",
        f"#define {GUARD}",
        "",
        "#define CV_FOR_EACH_VECTOR_INTENT_MARKER(EMIT) \\",
    ]
    for index, row in enumerate(rows):
        args = ", ".join(f'"{value}"' for value in row)
        cont = " \\" if index < len(rows) - 1 else ""
        lines.append(f"  EMIT({args}){cont}")
    lines.append("")
    lines.append(f"#endif  // {GUARD}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--facts", type=Path, default=DEFAULT_FACTS)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--out", type=Path)
    mode.add_argument("--check", type=Path)
    args = ap.parse_args()

    generated = render(args.facts)

    if args.check:
        existing = args.check.read_text(encoding="utf-8") if args.check.exists() else ""
        if existing == generated:
            print(f"vector-intent-header: OK, {args.check.name} matches semantic_facts.json")
            return 0
        sys.stdout.writelines(difflib.unified_diff(
            existing.splitlines(keepends=True), generated.splitlines(keepends=True),
            fromfile="committed", tofile="generated", n=1))
        print("vector-intent-header: DRIFT -- regenerate with --out", file=sys.stderr)
        return 1

    out = args.out or DEFAULT_OUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generated, encoding="utf-8")
    print(f"vector-intent-header: wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
