#!/usr/bin/env python3
"""Generate the KLEE oracle-novelty feedback header.

KLEE explores `GeneratorConfig` by forking on probe predicates, so a fresh run
keeps re-deriving the same easy markers. This tool turns prior coverage into a
feedback constraint: it writes `GeneratedKleeFeedback.h` listing the markers
already generated, plus an `isNovelCoverage(coverage)` predicate that is true only
when a config hits at least one *not-yet-covered* marker. Built with
`-DO2T_KLEE_FEEDBACK`, the harness `klee_assume`s that predicate, so
KLEE prunes paths that only reproduce covered markers and spends its budget on
the frontier. Across runs the covered set accumulates in a small JSON state file.

Covered markers can come from `--state` (accumulated JSON), `--covered-json`
(a coverage summary's `markers.generated`), and/or `--markers` (CSV); they are
unioned. `--out` writes the header; `--update-state` writes the union back.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HEADER_TEMPLATE = """\
#pragma once
// Generated by cv-generate-klee-feedback.py. Do not edit by hand.
//
// Covered probe markers fed back into the KLEE harness: with
// -DO2T_KLEE_FEEDBACK the harness assumes isNovelCoverage(), pruning
// configs that only re-derive already-covered markers.

#include "o2t/GeneratedProbeMarkerMap.h"

#include <cstddef>
#include <cstring>

namespace cv {{

inline constexpr const char *kCoveredMarkers[] = {{
{entries}    nullptr,
}};

inline constexpr std::size_t kCoveredMarkerCount = {count};

inline bool markerCovered(const char *marker) {{
  for (std::size_t i = 0; i < kCoveredMarkerCount; ++i) {{
    if (std::strcmp(kCoveredMarkers[i], marker) == 0) {{
      return true;
    }}
  }}
  return false;
}}

// True when the config hits at least one marker not yet in the covered set.
inline bool isNovelCoverage(const PassProbeCoverage &coverage) {{
  for (const ProbeMarkerMetadata &meta : kProbeMarkerMetadata) {{
    if (coverage.*meta.coverage && !markerCovered(meta.marker)) {{
      return true;
    }}
  }}
  return false;
}}

}} // namespace cv
"""


def collect_markers(args: argparse.Namespace) -> set[str]:
    covered: set[str] = set()
    if args.state and args.state.exists():
        data = json.loads(args.state.read_text())
        covered.update(data.get("covered", []))
    if args.covered_json:
        data = json.loads(args.covered_json.read_text())
        covered.update(data.get("markers", {}).get("generated", []))
    if args.markers:
        covered.update(m.strip() for m in args.markers.split(",") if m.strip())
    return covered


def render_header(covered: set[str]) -> str:
    ordered = sorted(covered)
    entries = "".join(f'    "{m}",\n' for m in ordered)
    return HEADER_TEMPLATE.format(entries=entries, count=len(ordered))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--state", type=Path, help="accumulated covered-markers JSON")
    parser.add_argument("--covered-json", type=Path, help="coverage-summary.json")
    parser.add_argument("--markers", help="comma-separated marker names")
    parser.add_argument("--out", type=Path, help="write the feedback header here")
    parser.add_argument("--update-state", type=Path,
                        help="write the unioned covered set back to this JSON")
    args = parser.parse_args()

    covered = collect_markers(args)

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(render_header(covered))
    if args.update_state:
        args.update_state.parent.mkdir(parents=True, exist_ok=True)
        args.update_state.write_text(
            json.dumps({"covered": sorted(covered)}, indent=2) + "\n")

    print(f"feedback: {len(covered)} covered marker(s)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
