#!/usr/bin/env python3
"""Generate the C++ miner's built-in operation-idiom defaults from llvm_idioms.json.

The AST miner (cv-mine-pass-source-ast.cpp) loads constraints/llvm_idioms.json at
runtime, but keeps a HARDCODED fallback copy in installDefaultLlvmIdioms() used
when the JSON can't be read. That fallback drifted from the JSON (e.g. it lacked
the shl/lshr/ashr shift operations). This tool regenerates the operation block of
that fallback as an X-macro header so the two can never diverge -- adding an op
once in llvm_idioms.json now propagates to both the runtime load AND the C++
default.

  --out FILE     write the generated header
  --check FILE   regenerate and diff against FILE; exit 1 on drift (CI guard)
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_IDIOMS = ROOT / "constraints" / "llvm_idioms.json"
DEFAULT_OUT = ROOT / "include" / "o2t" / "GeneratedLlvmIdioms.h"
GUARD = "O2T_GENERATED_LLVM_IDIOMS_H"


def cxx_list(items: list[str]) -> str:
    return "{" + ", ".join(f'"{item}"' for item in items) + "}"


def render(idioms_path: Path) -> str:
    data = json.loads(idioms_path.read_text(encoding="utf-8"))
    operations = data.get("operations")
    if not isinstance(operations, list):
        raise ValueError("llvm_idioms.json must contain an 'operations' array")

    rows: list[tuple[str, str, str, str]] = []
    for op in operations:
        name = str(op.get("operation") or "")
        if not name:
            raise ValueError("each operation must have a non-empty 'operation'")
        matchers = [str(m) for m in op.get("matchers", []) if str(m)]
        builders = [str(b) for b in op.get("builders", []) if str(b)]
        commutative = "true" if op.get("commutative") else "false"
        rows.append((name, cxx_list(matchers), cxx_list(builders), commutative))
    rows.sort(key=lambda r: r[0])  # deterministic output

    width = max((len(f'AddOperation("{name}", ') for name, *_ in rows), default=0)
    lines = [
        "// GENERATED by tools/cv-generate-idiom-header.py from",
        "// constraints/llvm_idioms.json -- DO NOT EDIT.",
        "//",
        "// X-macro: invoke CV_FOR_EACH_GENERATED_OPERATION_IDIOM(AddOperation) where",
        "// AddOperation is callable as AddOperation(name, {matchers}, {builders}, commutative).",
        f"#ifndef {GUARD}",
        f"#define {GUARD}",
        "",
        "#define CV_FOR_EACH_GENERATED_OPERATION_IDIOM(AddOperation) \\",
    ]
    for index, (name, matchers, builders, commutative) in enumerate(rows):
        call = f'  AddOperation("{name}", {matchers}, {builders}, {commutative});'
        cont = " \\" if index < len(rows) - 1 else ""
        lines.append(call + cont)
    lines.append("")

    # Identity constants -> source-intent value + matcher, for the scalar
    # source-intent helpers (identityValueForSourceIntent /
    # identityMatcherForSourceIntent). Only constants with a concrete
    # formal_value and a matcher are emitted (e.g. same-value, which has no
    # numeric value, is handled structurally in the miner, not via these tables).
    const_rows: list[tuple[str, str, str]] = []
    for const in data.get("constants", []):
        identity = str(const.get("identity") or "")
        value = const.get("formal_value")
        matchers = [str(m) for m in const.get("matchers", []) if str(m)]
        if not identity or value is None or not matchers:
            continue
        const_rows.append((identity, str(int(value)), matchers[0]))
    const_rows.sort(key=lambda r: r[0])
    lines.append("// EMIT(identity, value, matcher)")
    lines.append("#define CV_FOR_EACH_GENERATED_IDENTITY_CONSTANT(EMIT) \\")
    for index, (identity, value, matcher) in enumerate(const_rows):
        cont = " \\" if index < len(const_rows) - 1 else ""
        lines.append(f'  EMIT("{identity}", "{value}", "{matcher}"){cont}')
    lines.append("")

    lines.append(f"#endif  // {GUARD}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--idioms", type=Path, default=DEFAULT_IDIOMS)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--out", type=Path, help="write the header here")
    mode.add_argument("--check", type=Path, help="diff against this committed header")
    args = ap.parse_args()

    generated = render(args.idioms)

    if args.check:
        existing = args.check.read_text(encoding="utf-8") if args.check.exists() else ""
        if existing == generated:
            print(f"idiom-header: OK, {args.check.name} matches llvm_idioms.json")
            return 0
        diff = difflib.unified_diff(
            existing.splitlines(keepends=True), generated.splitlines(keepends=True),
            fromfile="committed", tofile="generated", n=1)
        sys.stdout.writelines(diff)
        print("idiom-header: DRIFT -- regenerate with --out", file=sys.stderr)
        return 1

    out = args.out or DEFAULT_OUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generated, encoding="utf-8")
    print(f"idiom-header: wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
